[2020-09-06-19:26:51]from sport : <class 'AttributeError'>'NoneType' object has no attribute 'find_all'<traceback object at 0x10F7D808>
[2020-09-06-19:32:38]from sport : <class 'AttributeError'>'NoneType' object has no attribute 'find_all'<traceback object at 0x10F7DF48>
[2020-09-06-19:43:59]from sport : <class 'AttributeError'>'NoneType' object has no attribute 'find'<traceback object at 0x111C7328>
[2020-09-06-20:01:37]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x138B9C28>
[2020-09-06-20:02:38]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x0127DE48>
[2020-09-06-20:03:38]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x012741A8>
[2020-09-06-20:04:40]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x11193FE8>
[2020-09-06-20:05:40]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x011D1828>
[2020-09-06-20:06:40]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x111933C8>
[2020-09-06-20:07:41]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x110DF608>
[2020-09-06-20:08:42]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x01275068>
[2020-09-06-20:09:43]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x138C3468>
[2020-09-06-20:10:44]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x10FA0D08>
[2020-09-06-20:11:45]from le360 : <class 'requests.exceptions.MissingSchema'>Invalid URL '#': No schema supplied. Perhaps you meant http://#?<traceback object at 0x1168E7A8>
[2020-09-06-20:42:04]from sport : <class 'AttributeError'>'NoneType' object has no attribute 'find_all'<traceback object at 0x11029EE8>
[2020-09-06-21:15:59]from sport : <class 'AttributeError'>'NoneType' object has no attribute 'find_all'<traceback object at 0x11129388>
[2020-09-06-21:22:33]from sport : <class 'AttributeError'>'NoneType' object has no attribute 'find_all'<traceback object at 0x02D96728>
[2020-09-06-22:37:42]from sport : <class 'AttributeError'>'NoneType' object has no attribute 'find_all'<traceback object at 0x138BF648>
[2020-09-06-22:50:02]from le360 : <class 'AttributeError'>'NoneType' object has no attribute 'find_all'<traceback object at 0x1131D8E8>
[2020-09-06-22:50:32]from sport : <class 'AttributeError'>'NoneType' object has no attribute 'find_all'<traceback object at 0x10F42228>
[2020-09-06-23:07:04]from le360 : <class 'AttributeError'>'NoneType' object has no attribute 'find'<traceback object at 0x011F55A8>
[2020-09-07-09:14:27]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11571118>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))<traceback object at 0x00B33248>
[2020-09-07-09:15:27]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11571520>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))<traceback object at 0x02A74DE8>
[2020-09-07-09:16:27]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x115710E8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))<traceback object at 0x00B33248>
[2020-09-07-09:17:27]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x115712F8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))<traceback object at 0x02A74C68>
[2020-09-07-09:18:27]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11571598>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))<traceback object at 0x00B33248>
[2020-09-07-09:19:27]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11571220>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))<traceback object at 0x02A74A08>
[2020-09-07-09:20:27]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x11571508>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))<traceback object at 0x00B33248>
[2020-09-07-09:55:09]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03E360E8>: Failed to establish a new connection: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu'))<traceback object at 0x02BDBEC8>
[2020-09-07-10:04:35]from hespress : <class 'requests.exceptions.ConnectionError'>HTTPSConnectionPool(host='fr.hespress.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10EBE310>: Failed to establish a new connection: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu'))<traceback object at 0x02B015E8>
